### ISSUE TITLE
Some time not do Forming tip Macro

### ISSUE THREAD

**Issue by Tutankamon00** [moggieuk/Happy-Hare#63]
Hi, some time appear to not start the forming tip macro and eject filament direct why?
![immagine](https://github.com/moggieuk/Happy-Hare/assets/142754987/50e0e203-d400-4fab-bf14-5be5d537be4a)

**Comment by veloyage** [comment]
I think am having the same issue, it will seemingly randomly not do any tipforming, other times it works fine. No obvious pattern to it regarding gate or anything else I can think of.
I have set force_form_tip_standalone: 1 and am using a filament cutter with form_tip_macro: _MMU_CUT_TIP.

**Comment by veloyage** [comment]
From limited testing, this seems fixed in the latest version :)
It complains about nonexistent loading issues now, but thats another story.

**Comment by Tutankamon00** [comment]
issue is still here, loaded filament with T0, ok, restart klipper, mmu_eject and NO TIP FORMING!!!! Filament ejected direct!!!! please solve this issue, thank you
![immagine](https://github.com/moggieuk/Happy-Hare/assets/142754987/715af939-04d0-44e1-8607-a0379a417854)

**Comment by moggieuk** [comment]
I may some subtle changes which may help you but, you don't have a toolhead sensor... so if the MMU gets into trouble and has to recover position if doesn't have the extra information of whether the filament is in the extruder or not.  Under some conditions it can try other things like moving the extruder (retraction) and looking for encoder measurement, but other times this would be dangerous.   The net result is that sometimes (without toolhead sensor) Happy Hare will conclude something which isn't accurate.

Toolhead sensor is highly recommended if you can fit a reliable one into your extruder.
